name: 'AI Code Theme Analysis Action'
description: 'AI-powered GitHub Action that analyzes code changes in pull requests to identify and consolidate business themes using Claude AI'
author: '6529 Collections'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  
  # Deduplication Controls
  skip-batch-dedup:
    description: 'Skip batch deduplication during theme expansion'
    required: false
    default: 'true'
  skip-second-pass-dedup:
    description: 'Skip second-pass deduplication across batches'
    required: false
    default: 'true'
  skip-cross-level-dedup:
    description: 'Skip cross-level hierarchical deduplication'
    required: false
    default: 'true'
  
  
  # PRD Compliance Controls
  max-atomic-size:
    description: 'Maximum lines for atomic theme (from PRD)'
    required: false
    default: '15'
  
  re-evaluate-after-merge:
    description: 'Re-evaluate merged themes for expansion'
    required: false
    default: 'false'
    
  strict-atomic-limits:
    description: 'Enforce PRD atomic size limits strictly'
    required: false
    default: 'true'
  

outputs:
  themes:
    description: 'Detailed theme analysis with consolidation information'
  summary:
    description: 'Summary of the theme analysis'

branding:
  icon: 'eye'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'
