name: 'My First Action'
description: 'A basic GitHub Action'
author: 'Your Name'

inputs:
  greeting:
    description: 'Greeting message'
    required: false
    default: 'Hello'
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true

outputs:
  message:
    description: 'The greeting message'

runs:
  using: 'node20'
  main: 'dist/index.js'