name: 'AI Code Theme Analysis Action'
description: 'AI-powered GitHub Action that analyzes code changes in pull requests to identify and consolidate business themes using Claude AI'
author: '6529 Collections'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true
  
  # Deduplication Controls
  skip-batch-dedup:
    description: 'Skip batch deduplication during theme expansion'
    required: false
    default: 'false'
  skip-second-pass-dedup:
    description: 'Skip second-pass deduplication across batches'
    required: false
    default: 'false'
  skip-cross-level-dedup:
    description: 'Skip cross-level hierarchical deduplication'
    required: false
    default: 'false'
  
  # Threshold Controls
  cross-level-dedup-threshold:
    description: 'Similarity threshold for cross-level deduplication (0.0-1.0)'
    required: false
    default: '0.95'
  allow-overlap-merging:
    description: 'Allow merging themes with overlap relationship (not just duplicates)'
    required: false
    default: 'true'
  
  # Minimum Theme Count Controls
  min-themes-for-batch-dedup:
    description: 'Minimum theme count to trigger batch deduplication'
    required: false
    default: '5'
  min-themes-for-second-pass-dedup:
    description: 'Minimum theme count to trigger second-pass deduplication'
    required: false
    default: '10'
  min-themes-for-cross-level-dedup:
    description: 'Minimum theme count to trigger cross-level deduplication'
    required: false
    default: '20'
  
  # Logging Controls
  verbose-dedup-logging:
    description: 'Enable detailed logging of deduplication decisions'
    required: false
    default: 'false'

outputs:
  themes:
    description: 'Detailed theme analysis with consolidation information'
  summary:
    description: 'Summary of the theme analysis'

branding:
  icon: 'eye'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'