name: 'AI Code Review Action'
description: 'AI-powered code review GitHub Action that provides automated code analysis and feedback'
author: '6529 Collections'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true

branding:
  icon: 'eye'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'