name: 'AI Code Theme Analysis Action'
description: 'AI-powered GitHub Action that analyzes code changes in pull requests to identify and consolidate business themes using Claude AI'
author: '6529 Collections'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  anthropic-api-key:
    description: 'Anthropic API key for Claude access'
    required: true

outputs:
  themes:
    description: 'Detailed theme analysis with consolidation information'
  summary:
    description: 'Summary of the theme analysis'

branding:
  icon: 'eye'
  color: 'blue'

runs:
  using: 'node20'
  main: 'dist/index.js'