import * as core from '@actions/core';
import * as github from '@actions/github';
import { validateInputs } from './validation';
import { handleError, logInfo, setOutput } from './utils';

export async function run(): Promise<void> {
  try {
    const inputs = validateInputs();

    logInfo(`Processing greeting: ${inputs.greeting}`);
    logInfo('Starting code review analysis...');
    const message: string = `${inputs.greeting} from GitHub Actions!`;

    logInfo(`Generated message: ${message}`);
    setOutput('message', message);

    // Add job summary (visible in Actions tab)
    await core.summary
      .addHeading('Code Review Results')
      .addRaw(`**Message:** ${message}`)
      .addSeparator()
      .addTable([
        ['File', 'Status', 'Issues'],
        ['src/index.ts', '✅ Clean', '0'],
        ['Example file', '⚠️ Warning', '1'],
      ])
      .write();

    // Add PR comment if this is a pull request
    const token = inputs.githubToken;
    if (token && github.context.eventName === 'pull_request') {
      const octokit = github.getOctokit(token);

      const commentBody = `## 🤖 AI Code Review Results

${message}

| File | Status | Issues |
|------|---------|---------|
| src/index.ts | ✅ Clean | 0 |
| Example file | ⚠️ Warning | 1 |

---
*Generated by AI Code Review Action*`;

      await octokit.rest.issues.createComment({
        ...github.context.repo,
        issue_number: github.context.issue.number,
        body: commentBody,
      });

      logInfo('PR comment added successfully');
    }
  } catch (error) {
    handleError(error);
  }
}

if (require.main === module) {
  run();
}
