name: Manual AI Code Review

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: true
        type: string
      action_branch:
        description: 'Branch to use for action code (default: main)'
        required: false
        type: string
        default: 'main'

# Permissions needed for commenting on PRs
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  manual-ai-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get PR details
      id: pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ github.event.inputs.pr_number }}
          });
          
          core.setOutput('head_sha', pr.data.head.sha);
          core.setOutput('base_sha', pr.data.base.sha);
          core.setOutput('head_ref', pr.data.head.ref);
          core.setOutput('base_ref', pr.data.base.ref);
          
          console.log(`PR #${{ github.event.inputs.pr_number }}: ${pr.data.title}`);
          console.log(`Head: ${pr.data.head.sha}`);
          console.log(`Base: ${pr.data.base.sha}`);
    
    - name: Checkout action code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.action_branch }}
        
    - name: Get PR code for analysis
      run: |
        echo "Fetching PR code for analysis..."
        git fetch origin pull/${{ github.event.inputs.pr_number }}/head:pr-${{ github.event.inputs.pr_number }}
        echo "PR code fetched, but action will run from ${{ github.event.inputs.action_branch }} branch"
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run AI Code Review (Full Pipeline)
      uses: ./
      id: review
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Only actual parameter from action.yml
        max-atomic-size: '15'
      env:
        LOG_LEVEL: INFO
        LOG_TIMESTAMPS: true
        NODE_ENV: production
        # Override context for manual PR review
        GITHUB_CONTEXT_ISSUE_NUMBER: ${{ github.event.inputs.pr_number }}
        # Ensure production mode (not development mode)
        DEV_MODE_PHASE2_ONLY: 'false'
    
    - name: Review Summary
      if: always()
      run: |
        echo "🤖 AI Code Review completed for PR #${{ github.event.inputs.pr_number }}"
        echo "✅ Full pipeline executed (Phase 1 + Phase 2)"
        echo "🔧 Action code from: ${{ github.event.inputs.action_branch }} branch"
        echo "Check the PR comments for detailed findings"
        echo "🔗 PR Link: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.inputs.pr_number }}"