name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch enough history for proper diff comparison
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Test the action
      uses: ./
      id: review
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
    
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🤖 AI Code Review Results
            
            **Themes:** ${{ steps.review.outputs.themes }}
            
            **Summary:** ${{ steps.review.outputs.summary }}
            
            ---
            *Generated by AI Code Review Action*`
          })