name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch enough history for proper diff comparison
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Test the action
      uses: ./
      id: review
      with:
        anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        # Use defaults from action.yml which skip child deduplication
        # skip-batch-dedup: 'true' (default)
        # skip-second-pass-dedup: 'true' (default)
        cross-level-dedup-threshold: '0.95'
        allow-overlap-merging: 'false'
        min-themes-for-cross-level-dedup: '5'
        min-themes-for-second-pass-dedup: '5'
        verbose-dedup-logging: 'true'
        # PRD Compliance
        max-atomic-size: '15'
        re-evaluate-after-merge: 'true'
        strict-atomic-limits: 'true'
      env:
        LOG_LEVEL: INFO
        LOG_TIMESTAMPS: true
    
    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const themes = ${{ toJSON(steps.review.outputs.themes) }};
          const summary = ${{ toJSON(steps.review.outputs.summary) }};
          
          // Handle null/undefined outputs
          const formattedThemes = themes ? (typeof themes === 'string' ? themes.replace(/\\n/g, '\n') : JSON.stringify(themes, null, 2)) : 'No themes available';
          const formattedSummary = summary ? (typeof summary === 'string' ? summary.replace(/\\n/g, '\n') : JSON.stringify(summary, null, 2)) : 'No summary available';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🤖 AI Code Review Results
            
            **Themes:** 
            ${formattedThemes}
            
            **Summary:** ${formattedSummary}
            
            ---
            *Generated by AI Code Review Action*`
          })
